# Generated by Django 5.0.6 on 2024-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APODImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('explanation', models.TextField()),
                ('hdurl', models.URLField()),
                ('media_type', models.CharField(max_length=50)),
                ('service_version', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
