# Generated by Django 5.0.6 on 2024-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apodimage',
            name='image_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
