# Generated by Django 5.0.6 on 2024-06-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_apodimage_image_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apodimage',
            name='hdurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
