# Generated by Django 5.0.6 on 2024-06-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_apodimage_hdurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apodimage',
            name='image_bytes',
        ),
    ]
