# Generated by Django 5.0.6 on 2024-06-26 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_apodimage_image_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apodimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apodimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
