# Generated by Django 5.0.6 on 2024-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_apodimage_created_at_apodimage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apodimage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.tag'),
        ),
    ]
